name: Run Entando Bundle Pack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-entando-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare workspace directory
        run: |
          mkdir -p .entando/logs
          chmod -R 777 .entando

      - name: Install OpenShift CLI
        run: |
          curl -L -o oc.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xzf oc.tar.gz
          chmod +x oc
          sudo mv oc /usr/local/bin/

      - name: Run Entando Bundle Pack
        env:
          OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
          OPENSHIFT_USER: ${{ secrets.OPENSHIFT_USER }}
          OPENSHIFT_PASSWORD: ${{ secrets.OPENSHIFT_PASSWORD }}
        run: |
          oc login --server="$OPENSHIFT_SERVER" --username="$OPENSHIFT_USER" --password="$OPENSHIFT_PASSWORD" --insecure-skip-tls-verify=true
          docker run --rm \
            -v "$(pwd):/workspace" \
            -w /workspace \
            -u 0:0 \
            docker.io/entando/ent:v7.3.0-mt \
            sh -c "ent bundle pack --org=mescalo && ent bundle publish --org=mescalo && ent appname portali && ent namespace portali-entando && ent bundle install"
