name: Run Entando Bundle Pack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-entando-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare workspace directory
        run: |
          mkdir -p .entando/logs
          chmod -R 777 .entando
      - name: Run Entando Bundle Pack
        run: |
          docker run --rm \
            -v "$(pwd):/workspace" \
            -w /workspace \
            -u 0:0 \
            docker.io/entando/ent:v7.3.0-mt \
            ent bundle pack --org=mescalo
  publish-entando-bundle:
    runs-on: ubuntu-latest
    needs: run-entando-bundle
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare workspace directory
        run: |
          mkdir -p .entando/logs
          chmod -R 777 .entando
      - name: Run Entando Bundle Publish
        run: |
          docker run --rm \
            -v "$(pwd):/workspace" \
            -w /workspace \
            -u 0:0 \
            docker.io/entando/ent:v7.3.0-mt \
            ent bundle publish --org=mescalo
          ent namespace portali-entando
          ent bundle generate-cr > bundle.yaml
          oc apply -f bundle.yaml -n portali-entando
          ent bundle install --conflict-strategy=OVERRIDE
