name: Run Entando Bundle Pack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-entando-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Entando Bundle Pack
        run: |
          docker run --rm \
            -v "$(pwd):/workspace" \
            -w /workspace \
            docker.io/entando/ent:v7.3.0-mt \
            ent bundle pack
