name: Run Entando Bundle Pack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-entando-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with OpenShift API
        run: |
          TOKEN=$(curl -k -X POST -u "${{ secrets.OPENSHIFT_USER }}:${{ secrets.OPENSHIFT_PASSWORD }}" \
            "${{ secrets.OPENSHIFT_SERVER }}/oauth/authorize?response_type=token&client_id=openshift-challenging-client" | jq -r .access_token)
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Prepare workspace directory
        run: |
          mkdir -p .entando/logs
          chmod -R 777 .entando

      - name: Run Entando Bundle Pack
        run: |
          docker run --rm \
            -v "$(pwd):/workspace" \
            -w /workspace \
            -u 0:0 \
            docker.io/entando/ent:v7.3.0-mt \
            sh -c "ent bundle pack --org=mescalo && ent bundle publish --org=mescalo && ent appname portali && ent namespace portali-entando && ent bundle install"
