name: Run Entando Bundle Pack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-entando-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare workspace directory
        run: |
          mkdir -p .entando/logs
          chmod -R 777 .entando

      - name: Run Entando Bundle Pack
        run: |
          docker run --rm \
            -v "$(pwd):/workspace" \
            -w /workspace \
            -u 0:0 \
            docker.io/mescalo/ent:github1 \
            sh -c "oc login --server=${{ secrets.OPENSHIFT_SERVER }} --username=${{ secrets.OPENSHIFT_USER }} --password=${{ secrets.OPENSHIFT_PASSWORD }} --insecure-skip-tls-verify=true && ent bundle pack --org=mescalo && ent bundle publish --org=mescalo && ent appname portali && ent namespace portali-entando && ent bundle install"
